import { chromium } from 'playwright-core';
import { readFileSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import http from 'node:http';
import assert from 'node:assert/strict';
const fixture = JSON.parse(execFileSync(process.execPath, ['node_modules/vite-node/vite-node.mjs', 'scripts/grid-fixture.ts'], { encoding: 'utf8' }));
const flightFixture = JSON.parse(execFileSync(process.execPath, ['node_modules/vite-node/vite-node.mjs', 'scripts/grid-fixture.ts', '--flight'], { encoding: 'utf8' }));
const recoveryFixture = JSON.parse(execFileSync(process.execPath, ['node_modules/vite-node/vite-node.mjs', 'scripts/grid-fixture.ts', '--recovery'], { encoding: 'utf8' }));
const panicFixture = JSON.parse(execFileSync(process.execPath, ['node_modules/vite-node/vite-node.mjs', 'scripts/grid-fixture.ts', '--panic'], { encoding: 'utf8' }));
const html = readFileSync('panel/dist/index.html', 'utf8');
const hostHtml = `<!doctype html><script>
const vars = {panel: ${JSON.stringify(fixture)}};
window.TavernHelper = {getVariables:()=>vars, insertOrAssignVariables:(value)=>{if(window.failSave)throw Error('test save failure');Object.assign(vars,value);}};
window.SillyTavern={getContext:()=>({chatId:'grid-test',characterId:0,characters:[{avatar:'test.png'}]})};
window.readBattle=()=>vars.panel.battle.snap;
window.loadFixture=(save)=>{vars.panel=save;localStorage.clear();};
</script><iframe id="panel" style="border:0;position:fixed;inset:0;width:100%;height:100%"></iframe>`;
const server = http.createServer((_req, res) => { res.setHeader('content-type', 'text/html;charset=utf-8'); res.end(hostHtml); });
await new Promise((r) => server.listen(0, '127.0.0.1', r));
const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
const errors = [];
try {
  const page = await browser.newPage({ viewport: { width: 1024, height: 844 } });
  page.on('pageerror', (e) => errors.push(e.message));
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await page.evaluate((html) => { document.querySelector('#panel').srcdoc = html; }, html);
  const p = page.frameLocator('#panel'); await p.locator('.grid-board').waitFor();
  const selectUnit = async (id) => {
    const select = p.locator('[data-role="grid-unit"]');
    if (!await select.isVisible()) await p.locator('.command-more summary').click();
    await select.selectOption(id);
  };
  const selectTarget = async (id) => {
    if (!await p.locator('[data-role="grid-target"]').isVisible()) await p.locator('.command-modes button').filter({ hasText: '攻击' }).click();
    await p.locator('[data-role="grid-target"]').selectOption(id);
  };
  await p.locator('.command-modes button').filter({ hasText: '守备' }).click();
  await p.locator('[data-action="grid-brace"]').click();
  const braced = await page.evaluate(() => window.readBattle());
  assert.equal(braced.combatants.find((u)=>u.id==='a').tacticalPose.kind, 'brace');
  assert.equal(braced.actedThisTurn.includes('a'), true);
  assert.equal(await p.locator('[data-action="grid-brace"]').isDisabled(), true);
  await page.evaluate((html) => { document.querySelector('#panel').srcdoc = html; }, html);
  await p.locator('.grid-board').waitFor();
  assert.match(await p.locator('.grid-command').innerText(), /固守朝/);
  await p.locator('[data-action="grid-cell"][data-cell="35"]').click(); await p.locator('[data-action="grid-move"]').click();
  assert.equal(await page.evaluate(() => window.readBattle().combatants.find((u)=>u.id==='a').tacticalPose), undefined);
  assert.equal(await page.evaluate(() => window.readBattle().actedThisTurn.includes('a')), true);
  console.log('✓ 正式固守：主行动扣除→自动朝向→重开保留→移动取消，行动不返还');
  const mobile = structuredClone(fixture);
  const mobileSource = { id: 'march-training', name: '急行训练', kind: 'blessing', traitIds: ['fast'], duration: { kind: 'battles', count: 1 }, remaining: 1 };
  mobile.storage.find((r)=>r.id==='a').snapshot.traitSources = [mobileSource];
  mobile.battle.snap.combatants.find((u)=>u.id==='a').traitSources = [mobileSource];
  mobile.battle.snap.combatants.find((u)=>u.id==='b').pos = 7;
  await page.evaluate(({ save, html }) => { window.loadFixture(save); document.querySelector('#panel').srcdoc = html; }, { save: mobile, html });
  await p.locator('.grid-board').waitFor();
  assert.match(await p.locator('.grid-budgets').innerText(), /移动 4\/4/);
  await p.locator('[data-action="grid-cell"][data-cell="14"]').click();
  assert.match(await p.locator('.move-preview').innerText(), /花费4移动/);
  await p.locator('[data-action="grid-move"]').click();
  assert.equal(await page.evaluate(() => window.readBattle().combatants.find((u)=>u.id==='a').pos), 14);
  await p.locator('[data-action="grid-endturn"]').click();
  assert.equal(await page.evaluate(() => window.readBattle().combatants.find((u)=>u.id==='a').fatigue), 1);
  await page.evaluate((html) => { document.querySelector('#panel').srcdoc = html; }, html); await p.locator('.grid-board').waitFor();
  assert.equal(await page.evaluate(() => window.readBattle().combatants.find((u)=>u.id==='a').fatigue), 1);
  console.log('✓ 正式机动：来源专长增加4点预算→真实移动4格→激活结束产生疲劳→重开保留');
  await page.evaluate(({ save, html }) => { window.loadFixture(save); document.querySelector('#panel').srcdoc = html; }, { save: fixture, html });
  await p.locator('.grid-board').waitFor();
  const before = await page.evaluate(() => JSON.stringify(window.readBattle()));
  await p.locator('[data-action="grid-cell"][data-cell="35"]').click();
  assert.equal(await page.evaluate(() => JSON.stringify(window.readBattle())), before, '点选与预览不得修改战斗');
  await p.locator('[data-action="grid-move"]').click();
  assert.equal(await page.evaluate(() => window.readBattle().combatants.find((u)=>u.id==='a').pos), 35);
  await selectTarget('b');
  await p.locator('[data-action="grid-execute"]').click();
  assert.equal(await page.evaluate(() => window.readBattle().actedThisTurn.includes('a')), true);
  await p.locator('[data-action="grid-cell"][data-cell="36"]').click();
  await p.locator('[data-action="grid-move"]').click();
  assert.equal(await page.evaluate(() => window.readBattle().combatants.find((u)=>u.id==='a').pos), 36);
  console.log('✓ 正式面板：点格→路径预览→移动→攻击→再移动');
  mkdirSync('panel/smoke-shots', { recursive: true });
  const stable = await page.evaluate(() => JSON.stringify(window.readBattle()));
  await p.locator('[data-action="theme-toggle"]').first().click();
  await p.locator('[data-action="theme-toggle"]').first().click();
  assert.equal(await page.evaluate(() => JSON.stringify(window.readBattle())), stable);
  if (!process.argv.includes('--skip-layout')) for (const width of [320, 390, 736, 1024]) {
    await page.setViewportSize({ width, height: width === 320 ? 568 : 844 });
    for (const theme of ['dark', 'light']) {
      await p.locator('body').evaluate((el, value) => { el.dataset.theme = value; }, theme);
      const layout = await p.locator('.tactical-workspace').evaluate((el) => {
        const cells = [...el.querySelectorAll('.grid-cell')]; const box = el.getBoundingClientRect();
        return { count: cells.length, minWidth: Math.min(...cells.map((c)=>c.getBoundingClientRect().width)), minHeight: Math.min(...cells.map((c)=>c.getBoundingClientRect().height)),
          bodyOverflow: document.documentElement.scrollWidth - window.innerWidth, right: box.right, viewport: window.innerWidth };
      });
      assert.equal(layout.count,63); assert.ok(layout.minWidth>=44&&layout.minHeight>=44); assert.ok(layout.bodyOverflow<=1, JSON.stringify({width,theme,...layout}));
      // 相机滚到四角，每个角格均能进入局部视窗；不改变战场或随机状态。
      for (const cell of [0,6,56,62]) {
        await p.locator(`[data-cell="${cell}"]`).evaluate((el) => el.scrollIntoView({block:'nearest',inline:'nearest'}));
        const visible = await p.locator(`[data-cell="${cell}"]`).evaluate((el) => { const a=el.getBoundingClientRect(), b=el.closest('.grid-camera').getBoundingClientRect(); return a.left>=b.left&&a.right<=b.right&&a.top>=b.top&&a.bottom<=b.bottom; });
        assert.ok(visible, `${width}/${theme} 无法访问角格${cell}`);
      }
      await p.locator('[data-action="grid-focus"]').click();
      await p.locator('.tactical-workspace').evaluate((el)=>el.scrollIntoView({block:'start'}));
      await page.screenshot({ path: `panel/smoke-shots/grid-${width}-${theme}.png` });
      assert.equal(await page.evaluate(() => JSON.stringify(window.readBattle())), stable);
      console.log(`✓ ${width}/${theme}：63格可访问，触控≥44px，无页面横溢出，相机/主题不改战斗`);
    }
  }
  await page.evaluate(({ save, html }) => { window.loadFixture({ ...save, battle: null }); document.querySelector('#panel').srcdoc = html; }, { save: fixture, html });
  await p.locator('.preparation-options summary').click();
  await p.locator('[data-role="map-layout"]').selectOption('indoor');
  await p.locator('[data-role="objective-mode"]').selectOption('escort');
  await p.locator('[data-action="small-start"]').click();
  await p.locator('.grid-board').waitFor();
  const indoor = await page.evaluate(() => window.readBattle().battlefield);
  assert.equal(indoor.width, 5); assert.equal(indoor.height, 7); assert.equal(indoor.objective.kind, 'escape'); assert.equal(indoor.objective.unitId, 'a');
  assert.equal(await p.locator('.grid-cell').count(), 35);
  console.log('✓ 正式开战入口选择5×7室内及护送主控，任务/地图进入战斗快照');
  for (const env of ['forest', 'mountain']) {
    await page.evaluate(({ save, html, env }) => { window.loadFixture({ ...save, battle: null, field: env, lighting: 'night', mapLayout: 'standard', objectiveMode: 'control' }); document.querySelector('#panel').srcdoc = html; }, { save: fixture, html, env });
    await p.locator('[data-action="small-start"]').click(); await p.locator('.grid-board').waitFor();
    const scene = await page.evaluate(() => window.readBattle());
    assert.ok(scene.fieldTags.includes(env) && scene.fieldTags.includes('night'));
    assert.ok(scene.battlefield.tiles.includes(env === 'forest' ? 'forest' : 'hill'));
    await selectUnit(scene.turnOrder[scene.turnIndex]);
    assert.match(await p.locator('.grid-budgets').innerText(), /移动 2\/2/);
    assert.match(await p.locator('.tactical-heading').innerText(), /夜间/);
    const frozen = JSON.stringify(scene);
    await page.evaluate((html) => { document.querySelector('#panel').srcdoc = html; }, html); await p.locator('.grid-board').waitFor();
    assert.equal(await page.evaluate(() => JSON.stringify(window.readBattle())), frozen);
    await page.setViewportSize({ width: 390, height: 844 });
    await p.locator('.tactical-workspace').evaluate((el)=>el.scrollIntoView({block:'start'}));
    await page.screenshot({ path: `panel/smoke-shots/environment-${env}-night-390.png` });
    assert.ok(await p.locator('body').evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    console.log(`✓ 正式场景：${env}/night自动生成→真实夜间移动预算→重开锁定→390px无横溢出`);
  }
  const night = structuredClone(fixture); night.battle.snap.fieldTags = ['plains', 'night']; night.battle.snap.battlefield.environment = ['plains', 'night']; night.battle.snap.battlefield.tiles.fill('open');
  night.battle.snap.combatants.find((u) => u.id === 'a').pos = 56;
  night.battle.snap.combatants.find((u) => u.id === 'b').pos = 0;
  for (const u of night.battle.snap.combatants.filter((u) => u.side === 'enemy')) u.name = '夜间隐藏目标';
  for (const r of night.storage.filter((u) => u.side === 'enemy')) { r.name = '夜间隐藏目标'; if (r.snapshot) r.snapshot.name = '夜间隐藏目标'; }
  night.battle.snap.log = [];
  await page.evaluate(({ save, html }) => { window.loadFixture(save); document.querySelector('#panel').srcdoc = html; }, { save: night, html });
  await p.locator('.grid-board').waitFor();
  assert.ok(!(await p.locator('body').innerText()).includes('夜间隐藏目标'), '地图以外的编制/库存/摘要也不能泄漏隐藏敌军');
  assert.ok(await p.locator('.grid-cell.unobserved').count() > 0);
  assert.equal(await p.locator('[data-role="grid-unit"] option[value="b"]').count(), 0);
  assert.equal(await p.locator('[data-role="grid-target"] option[value="b"]').count(), 0);
  const hiddenSnapshot = await page.evaluate(() => JSON.stringify(window.readBattle()));
  await page.evaluate((html) => { document.querySelector('#panel').srcdoc = html; }, html); await p.locator('.grid-board').waitFor();
  assert.equal(await page.evaluate(() => JSON.stringify(window.readBattle())), hiddenSnapshot);
  assert.ok(!(await p.locator('body').innerText()).includes('夜间隐藏目标'));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'panel/smoke-shots/observation-night-390.png' });
  console.log('✓ 夜间正式面板：暗区/地图/候选/编制/库存均无隐藏敌军，重开保留观测且不改快照');
  const stealth = structuredClone(fixture); stealth.battle.snap.battlefield.tiles.fill('open'); stealth.battle.snap.log = [];
  const hiddenActor = stealth.battle.snap.combatants.find((u) => u.id === 'a'); hiddenActor.pos = 45;
  hiddenActor.traitSources = [{ id: 'stalk-source', name: '林神隐蔽', kind: 'blessing', traitIds: ['stalk'], duration: { kind: 'permanent' } }];
  stealth.battle.snap.battlefield.tiles[45] = 'forest'; stealth.battle.snap.combatants.find((u) => u.id === 'b').pos = 24;
  // 固定失能靶标只验证暴露/休整交互，不把这条功能验收当作AI对抗或平衡证据。
  for (const u of stealth.battle.snap.combatants.filter((u) => u.side === 'enemy')) u.conditions = [{ id: 'stunned', dur: 99 }];
  await page.evaluate(({ save, html }) => { window.loadFixture(save); document.querySelector('#panel').srcdoc = html; }, { save: stealth, html });
  await p.locator('.grid-board').waitFor(); await selectUnit('a');
  assert.match(await p.locator('.grid-command').innerText(), /潜伏中/);
  await selectTarget('b');
  assert.ok(await p.locator('[data-action="grid-execute"]').isEnabled(), await p.locator('.action-preview').innerText());
  await p.locator('[data-action="grid-execute"]').click();
  assert.equal(await page.evaluate(() => window.readBattle().combatants.find((u) => u.id === 'a').tacticalRevealed), true);
  assert.match(await p.locator('.grid-command').innerText(), /已暴露/);
  await p.locator('[data-action="grid-endturn"]').click();
  assert.equal(await page.evaluate(() => window.readBattle().combatants.find((u) => u.id === 'a').tacticalRevealed), true, '攻击当次激活不能立即恢复隐匿');
  await selectUnit('c'); await p.locator('[data-action="grid-endturn"]').click();
  await selectUnit('a'); await p.locator('[data-action="grid-endturn"]').click();
  assert.equal(await page.evaluate(() => window.readBattle().combatants.find((u) => u.id === 'a').tacticalRevealed), undefined);
  await page.evaluate((html) => { document.querySelector('#panel').srcdoc = html; }, html); await p.locator('.grid-board').waitFor();
  await selectUnit('a'); assert.match(await p.locator('.grid-command').innerText(), /潜伏中/);
  await p.locator('.grid-command').evaluate((el) => el.scrollIntoView({ block: 'start' }));
  await page.screenshot({ path: 'panel/smoke-shots/stalk-rest-390.png' });
  console.log('✓ 潜伏正式面板：来源隐蔽→手动射击暴露→当次不能复隐→掩护完整休整→自动复隐/重开');
  const forward = structuredClone(fixture); forward.battle = null;
  // 正式开战使用随机先攻；固定本用例的我方先行，避免自动敌军抢先行动污染部署断言。
  const first = forward.storage.find((r) => r.id === 'a'); first.base.spd = 100; first.snapshot.base.spd = 100;
  for (const r of forward.storage.filter((r) => ['a', 'b'].includes(r.id))) { r.traits.push('vanguard'); r.snapshot.traits.push('vanguard'); }
  await page.evaluate(({ save, html }) => { window.loadFixture(save); document.querySelector('#panel').srcdoc = html; }, { save: forward, html });
  await p.locator('[data-action="small-start"]').click(); await p.locator('.grid-board').waitFor();
  const deployed = await page.evaluate(() => window.readBattle());
  assert.equal(Math.floor(deployed.combatants.find((u) => u.id === 'a').pos / 7), 5); assert.equal(Math.floor(deployed.combatants.find((u) => u.id === 'b').pos / 7), 3);
  assert.equal(deployed.movementSpent.length, 0); assert.equal(deployed.actedThisTurn.length, 0);
  await page.evaluate((html) => { document.querySelector('#panel').srcdoc = html; }, html); await p.locator('.grid-board').waitFor();
  assert.equal(await page.evaluate(() => JSON.stringify(window.readBattle())), JSON.stringify(deployed));
  console.log('✓ 小战先锋：真实开战前出1排，完整行动预算，重开不重复前出');
  await page.evaluate(({ save, html }) => { window.loadFixture(save); document.querySelector('#panel').srcdoc = html; }, { save: flightFixture, html });
  await p.locator('.grid-board').waitFor(); await selectUnit('a');
  assert.equal(await page.evaluate(() => window.readBattle().combatants.find((u) => u.id === 'a').airborne), true);
  const flightBefore = await page.evaluate(() => JSON.stringify(window.readBattle()));
  await p.locator('body').evaluate(() => { const original = Storage.prototype.setItem; Storage.prototype.setItem = function (...args) { if (window.parent.failSave) throw Error('test quota'); return original.apply(this, args); }; });
  await page.evaluate(() => { window.failSave = true; });
  await p.locator('[data-action="grid-flight"]').click(); assert.equal(await page.evaluate(() => JSON.stringify(window.readBattle())), flightBefore);
  assert.match(await p.locator('[data-role="save-status"]').innerText(), /未保存/); await page.evaluate(() => { window.failSave = false; });
  await p.locator('[data-action="grid-flight"]').click();
  assert.equal(await page.evaluate(() => window.readBattle().combatants.find((u) => u.id === 'a').airborne), false);
  assert.equal(await page.evaluate(() => new Map(window.readBattle().movementSpent).get('a')), 1);
  await p.locator('[data-action="grid-flight"]').click(); const flightAfter = await page.evaluate(() => JSON.stringify(window.readBattle()));
  await page.evaluate((html) => { document.querySelector('#panel').srcdoc = html; }, html); await p.locator('.grid-board').waitFor();
  assert.equal(await page.evaluate(() => JSON.stringify(window.readBattle())), flightAfter);
  await page.evaluate(({ save, html }) => { window.loadFixture(save); document.querySelector('#panel').srcdoc = html; }, { save: flightFixture, html });
  await p.locator('.grid-board').waitFor(); await p.locator('[data-action="grid-cell"][data-cell="28"]').click(); await p.locator('[data-action="grid-move"]').click();
  await selectTarget('b'); assert.match(await p.locator('.action-preview').innerText(), /先降落/);
  await p.locator('.grid-command').evaluate((el) => el.scrollIntoView({ block: 'start' })); await page.screenshot({ path: 'panel/smoke-shots/flight-dive-390.png' });
  await p.locator('[data-action="grid-execute"]').click(); const dive = await page.evaluate(() => window.readBattle());
  assert.equal(dive.combatants.find((u) => u.id === 'a').airborne, false); assert.equal(new Map(dive.movementSpent).get('a'), 3); assert.ok(dive.actedThisTurn.includes('a'));
  console.log('✓ 小战飞行：真实升空→起落保存失败回退→同一移动账本/重开→扑击预览→移动加降落/主行动实际扣除');
  await page.evaluate(({ save, html }) => { window.loadFixture(save); document.querySelector('#panel').srcdoc = html; }, { save: recoveryFixture, html }); await p.locator('.grid-board').waitFor();
  const recoveryBefore = await page.evaluate(() => JSON.stringify(window.readBattle()));
  await p.locator('body').evaluate(() => { const original = Storage.prototype.setItem; Storage.prototype.setItem = function (...args) { if (window.parent.failSave) throw Error('test quota'); return original.apply(this, args); }; }); await page.evaluate(() => { window.failSave = true; });
  await p.locator('[data-action="grid-endturn"]').click(); assert.equal(await page.evaluate(() => JSON.stringify(window.readBattle())), recoveryBefore);
  await page.evaluate(() => { window.failSave = false; }); await p.locator('[data-action="grid-endturn"]').click();
  let healed = await page.evaluate(() => window.readBattle()); assert.equal(healed.combatants.find((u) => u.id === 'a').hp, 83); assert.equal(healed.combatants.find((u) => u.id === 'a').recoverableWounded, 7);
  await page.evaluate((html) => { document.querySelector('#panel').srcdoc = html; }, html); await p.locator('.grid-board').waitFor(); assert.equal(await page.evaluate(() => JSON.stringify(window.readBattle())), JSON.stringify(healed));
  for (let n = 0; n < 4; n++) await p.locator('[data-action="grid-endturn"]').click();
  healed = await page.evaluate(() => window.readBattle()); assert.equal(healed.combatants.find((u) => u.id === 'a').hp, 90); assert.equal(healed.combatants.find((u) => u.id === 'a').recoverableWounded, 0);
  console.log('✓ 小战伤兵：激活末再生保存失败回退→重试只恢复3/池减3→重开→耗尽伤兵后停在90/100');
  const moraleCase = structuredClone(fixture), ma = moraleCase.battle.snap.combatants.find((u) => u.id === 'a'), mf = moraleCase.battle.snap.combatants.find((u) => u.id === 'b');
  ma.pos = 45; mf.pos = 31; mf.traits.push('fear');
  await page.evaluate(({ save, html }) => { window.loadFixture(save); document.querySelector('#panel').srcdoc = html; }, { save: moraleCase, html }); await p.locator('.grid-board').waitFor();
  await selectUnit('a'); await selectTarget('b');
  assert.match(await p.locator('.grid-command .morale-pressure').innerText(), /恐惧压力8.*攻击降低1/);
  await page.setViewportSize({ width: 390, height: 844 }); await p.locator('.grid-command').evaluate((el) => el.scrollIntoView({ block: 'start' })); await page.screenshot({ path: 'panel/smoke-shots/morale-pressure-390.png' });
  await p.locator('[data-action="grid-execute"]').click(); let pressured = await page.evaluate(() => window.readBattle());
  assert.equal(pressured.log.find((l) => l.resolution?.attackerId === 'a').resolution.netAtk, ma.base.atk - 1);
  await p.locator('[data-action="grid-cell"][data-cell="59"]').click(); await p.locator('[data-action="grid-move"]').click(); assert.equal(await p.locator('.grid-command .morale-pressure').count(), 0);
  pressured = await page.evaluate(() => window.readBattle()); await page.evaluate((html) => { document.querySelector('#panel').srcdoc = html; }, html); await p.locator('.grid-board').waitFor(); assert.equal(await page.evaluate(() => JSON.stringify(window.readBattle())), JSON.stringify(pressured));
  console.log('✓ 小战近域恐惧：可读压力/攻击代价→实际射击减1→合法移出范围立即撤销→重开');
  await page.evaluate(({ save, html }) => { window.loadFixture(save); document.querySelector('#panel').srcdoc = html; }, { save: panicFixture, html }); await p.locator('.grid-board').waitFor();
  await selectUnit('a'); assert.match(await p.locator('.grid-command .morale-pressure').innerText(), /剩余2次机会/); assert.equal(await p.locator('[data-action="grid-execute"]').isEnabled(), false);
  const panicBefore = await page.evaluate(() => JSON.stringify(window.readBattle())); await page.evaluate((html) => { document.querySelector('#panel').srcdoc = html; }, html); await p.locator('.grid-board').waitFor(); assert.equal(await page.evaluate(() => JSON.stringify(window.readBattle())), panicBefore);
  await selectUnit('c'); await p.locator('body').evaluate(() => { const original = Storage.prototype.setItem; Storage.prototype.setItem = function (...args) { if (window.parent.failSave) throw Error('test quota'); return original.apply(this, args); }; }); await page.evaluate(() => { window.failSave = true; });
  await p.locator('[data-action="grid-endturn"]').click(); assert.equal(await page.evaluate(() => JSON.stringify(window.readBattle())), panicBefore);
  await page.evaluate(() => { window.failSave = false; }); await p.locator('[data-action="grid-endturn"]').click();
  await page.waitForFunction(() => window.readBattle().combatants.find((u) => u.id === 'a').status === 'ready');
  const rallied = await page.evaluate(() => window.readBattle()); assert.equal(rallied.combatants.find((u) => u.id === 'a').moraleState.attempts, 1); assert.deepEqual(rallied.combatants.find((u) => u.id === 'a').moraleState.terrorSeen, ['b']);
  console.log('✓ 小战惊退：引擎实际惊退→剩余机会/不可行动→重开不刷新→结束激活失败回退→重试推进至重整/同来源保留');
  assert.deepEqual(errors,[]);
} finally { await browser.close(); await new Promise((r)=>server.close(r)); }
