import { chromium } from 'playwright-core';
import { readFileSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import http from 'node:http';
import assert from 'node:assert/strict';
const fixture = JSON.parse(execFileSync(process.execPath, ['node_modules/vite-node/vite-node.mjs', 'scripts/migration-fixture.ts'], { encoding: 'utf8' }));
const html = readFileSync('panel/dist/index.html', 'utf8');
const server = http.createServer((_req, res) => { res.setHeader('content-type', 'text/html;charset=utf-8'); res.end(`<!doctype html><script>
window.failSave=false;const vars={panel:${JSON.stringify(fixture)}};
window.TavernHelper={getVariables:()=>vars,insertOrAssignVariables:(value)=>{if(window.failSave)throw Error('quota');Object.assign(vars,value)}};
window.SillyTavern={getContext:()=>({chatId:'migration-test',characterId:0,characters:[{avatar:'test.png'}]})};
window.readSave=()=>vars.panel;
</script><iframe id="panel" style="border:0;position:fixed;inset:0;width:100%;height:100%"></iframe>`); });
await new Promise((r) => server.listen(0, '127.0.0.1', r));
const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  page.setDefaultTimeout(10000);
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await page.evaluate((html) => { document.querySelector('#panel').srcdoc = html; }, html);
  const p = page.frameLocator('#panel'); await p.locator('[data-role="migration-review"]').waitFor();
  assert.deepEqual(await page.evaluate(() => window.readSave()), fixture);
  await p.locator('.workspace-nav [data-tab="settings"]').click();
  await p.locator('[data-action="save-retry"]').click();
  assert.deepEqual(await page.evaluate(() => window.readSave()), fixture);
  await page.evaluate(() => { window.failSave = true; });
  await p.locator('body').evaluate(() => { Storage.prototype.setItem = function () { if (window.parent.failSave) throw Error('quota'); }; });
  await p.locator('[data-action="migration-accept"]').click();
  await p.locator('[data-role="migration-review"]').waitFor();
  assert.deepEqual(await page.evaluate(() => window.readSave()), fixture);
  await page.evaluate(() => { window.failSave = false; });
  await p.locator('[data-action="migration-accept"]').click();
  let saved = await page.evaluate(() => window.readSave());
  assert.equal(saved.schemaVersion, 2); assert.equal(saved.storage[0].hp, 70); assert.equal(saved.storage[0].base.hpMax, 560);
  assert.deepEqual(saved.storage[0].snapshot.weapon, fixture.roster[0].weapon);
  assert.equal(saved.migrationBackups.length, 1);
  const migratedMook = saved.storage.find((r) => r.id === fixture.roster[1].id);
  assert.equal(migratedMook.scale, 'company'); assert.equal(migratedMook.hp, 7); assert.equal(migratedMook.base.hpMax, 20);
  assert.deepEqual(migratedMook.snapshot.weapon, fixture.roster[1].weapon);
  assert.deepEqual(saved.inventory, [fixture.inventory[0], fixture.inventory[2]]);
  assert.deepEqual(saved.inventoryMigrationBackup, [fixture.inventory[1]]);
  assert.deepEqual(saved.migrationBackups[0].source.inventory, fixture.inventory);
  await p.locator('.workspace-nav [data-tab="units"]').click();
  await p.locator('[data-action="manage-toggle"]').click();
  await p.locator('[data-action="unit-conversion-preview"]').click();
  await p.locator('[data-role="unit-conversion"]').waitFor();
  mkdirSync('panel/smoke-shots', { recursive: true });
  for (const width of [320, 390]) {
    await page.setViewportSize({ width, height: 844 });
    assert.ok(await p.locator('body').evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    await p.locator('[data-role="unit-conversion"]').evaluate((el) => el.scrollIntoView({ block: 'start' }));
    await page.screenshot({ path: `panel/smoke-shots/conversion-${width}.png` });
  }
  assert.notEqual((await page.evaluate(() => window.readSave())).storage[0].snapshot.rulesVersion, 'v2');
  await p.locator('[data-action="unit-conversion-commit"]').click();
  saved = await page.evaluate(() => window.readSave());
  assert.equal(saved.storage[0].snapshot.rulesVersion, 'v2'); assert.equal(saved.storage[0].hp, 70);
  assert.equal(saved.storage[0].snapshot.weapon.recipe.mechanism, 'rifle'); assert.ok(saved.storage[0].legacyRecord);
  await p.locator('[data-action="unit-conversion-undo"]').click();
  saved = await page.evaluate(() => window.readSave());
  assert.notEqual(saved.storage[0].snapshot.rulesVersion, 'v2'); assert.deepEqual(saved.storage[0].snapshot.weapon, fixture.roster[0].weapon);
  await p.locator('.workspace-nav [data-tab="settings"]').click();
  await p.getByText('迁移备份与恢复', { exact: true }).click();
  await p.locator('[data-action="migration-restore"]').click();
  await p.locator('[data-role="migration-review"]').waitFor();
  saved = await page.evaluate(() => window.readSave());
  assert.equal(saved.schemaVersion, 1); assert.deepEqual(saved.roster, fixture.roster);
  assert.deepEqual(saved.inventory, fixture.inventory);
  console.log('✓ 390px正式面板：只读/失败回退→旧V2刻度归编队并保留7/20和装备→坏库存隔离/完整备份→转制/撤销→恢复原始旧档');
} finally { await browser.close(); await new Promise((r) => server.close(r)); }
