import { describe, expect, it, vi } from 'vitest';
import { generatedField, generateUnit, generatedLayeredField, SmallBattle, V11_OVERFLOW_D20 } from '../../engine/src/index.js';
import { TavernJevAdapter } from './jev-adapter.js';
import { tacticalFixture } from '../../scripts/p4-tactical-fixture.js';
import { renderTacticalBattle, selectTacticalElement, tacticalSelection, type TacticalView } from './tactical-view.js';

describe('战术地图查看与确认', () => {
  it('shows named landmarks in the inspector and commander map without enabling new terrain rules', async () => {
    const { b } = tacticalFixture();
    b.battlefield!.generation = generatedField('ui-label', 7, 9, ['urban']).generation;
    b.battlefield!.generation!.landmark = { label: '废弃钟楼', cells: [44, 46], terrain: 'hill' };
    const html = renderTacticalBattle(b, { mode: 'weapon', selectedId: 'a', inspectedCell: 44 });
    expect(html).toContain('废弃钟楼'); expect(html).toContain('grid-landmark');
    expect(html).toContain('森林');
    const adapter = new TavernJevAdapter(b, 'ally', 'test', 0, new AbortController().signal);
    expect(JSON.stringify(await adapter.observe())).toContain('废弃钟楼');
    b.battlefield!.generation!.landmark.cells = 'broken' as unknown as number[];
    expect(() => renderTacticalBattle(b, { mode: 'weapon', selectedId: 'a' })).not.toThrow();
    b.battlefield!.generation!.landmark = { label: '<img src=x>', cells: [44], terrain: 'hill' };
    expect(renderTacticalBattle(b, { mode: 'weapon', selectedId: 'a' })).not.toContain('<img src=x>');
  });
  it('renders destructible city layers and legal actions without changing the battle', () => {
    const a = generateUnit({name:'先锋',side:'ally',scale:'hero',rulesVersion:'v2',level:3,weaponClass:'blunt',traits:['siege-assault']},{seed:'ui-a'}).unit;
    const b = generateUnit({name:'守军',side:'enemy',scale:'hero',rulesVersion:'v2',level:3,weaponClass:'bow',traits:[]},{seed:'ui-b'}).unit;
    const field = generatedLayeredField('city-ui',7,13,['siege'],{plan:{shape:'front',landmarks:[]}});
    const battle = new SmallBattle({battlefield:field,combatants:[a,b],rules:V11_OVERFLOW_D20,seed:'city-ui'}); battle.start(); battle.turnOrder=[a.id,b.id];battle.turnIndex=0;
    const cell = battle.battlefield!.city!.gates[0]!; a.pos = cell + field.width;
    const before = structuredClone(battle.toSnapshot());
    const html = renderTacticalBattle(battle,{mode:'weapon',selectedId:a.id,inspectedCell:cell});
    expect(html).toContain('grid-structure'); expect(html).toContain('grid-gate'); expect(html).toContain('grid-climb');
    expect(html).toContain('耐久'); expect(html).toContain('地面不可通行'); expect(html).toContain('control-region');
    expect(battle.toSnapshot()).toEqual(before);
  });
  it('隐藏未准备技能，保留装备和物品能力，并让过期技能选择回到武器', () => {
    const { b } = tacticalFixture(), actor = b.byId('a');
    const [removed, prepared] = actor.abilities;
    actor.preparedAbilityIds = [prepared!.id];
    actor.abilities.push({ ...prepared!, id: 'gear-skill', equipmentSourceId: 'gear' }, { ...prepared!, id: 'item-skill', itemSourceId: 'item' });
    const s = tacticalSelection(b, { mode: removed!.id, selectedId: actor.id });
    expect(s.options.filter(o => o.kind === 'ability').map(o => o.id)).toEqual([prepared!.id, 'gear-skill', 'item-skill']);
    expect(s.option?.id).toBe('weapon');
    expect(actor.abilities).toContain(removed);
  });
  it('同一次点选与渲染只查一次动作；换行动者或后续渲染重新查询', () => {
    const { b } = tacticalFixture(), view: TacticalView = { mode: 'weapon', selectedId: 'a' };
    const spy = vi.spyOn(b, 'getActionOptions');
    const query = selectTacticalElement(b, view, { cell: 31 });
    const reused = renderTacticalBattle(b, view, false, query);
    expect(spy).toHaveBeenCalledTimes(1);
    expect(renderTacticalBattle(b, view)).toBe(reused);
    expect(spy).toHaveBeenCalledTimes(2);
    view.selectedId = 'c'; renderTacticalBattle(b, view, false, query);
    expect(spy).toHaveBeenLastCalledWith('c');
    view.selectedId = 'a'; b.byId('a').conditions.push({ id: 'stunned', dur: 2 });
    renderTacticalBattle(b, view);
    expect(spy).toHaveBeenCalledTimes(4);
    expect(spy).toHaveBeenLastCalledWith('a');
    spy.mockRestore();
  });
  it('点选与渲染不改事实；敌军不成为查询者，治疗可点友军，同格友军可预览移动', () => {
    const { b } = tacticalFixture(), view: TacticalView = { mode: 'weapon', selectedId: 'a' };
    const before = JSON.stringify(b.toSnapshot()), query = vi.spyOn(b, 'getActionOptions');
    selectTacticalElement(b, view, { cell: 31 });
    const html = renderTacticalBattle(b, view);
    expect(html).toContain('命中率');
    expect(html).toContain('命中后伤害');
    expect(html).not.toContain('主目标预计损失');
    expect(html).not.toContain('期望已包含未命中');
    expect(html).toContain('无法穿透，不造成生命或人数损失');
    expect(html).toContain('连续守住2个完整回合');
    expect(html).not.toContain('未发现的伏兵');
    expect(tacticalSelection(b, view).target?.preview).toMatchObject({ penetrationFactor: 0, expectedDamage: 0 });
    const heal = b.byId('a').abilities.find((a) => a.definitionId === 'bp-mending')!;
    selectTacticalElement(b, view, { mode: heal.id }); selectTacticalElement(b, view, { cell: 44 });
    expect(view.selectedId).toBe('a'); expect(view.targetId).toBe('c');
    expect(tacticalSelection(b, view).target?.preview?.healing).toBeGreaterThan(0);
    selectTacticalElement(b, view, { mode: 'move' }); selectTacticalElement(b, view, { cell: 44 });
    expect(view.selectedId).toBe('a'); expect(view.cell).toBe(44);
    expect(b.pathPreview('a', view.cell!).path?.cost).toBe(2);
    renderTacticalBattle(b, view);
    view.selectedId = 'b'; renderTacticalBattle(b, view);
    expect(query.mock.calls.every(([id]) => b.byId(id).side === 'ally')).toBe(true);
    expect(JSON.stringify(b.toSnapshot())).toBe(before);
    query.mockRestore();
  });

  it('范围高亮与实际两目标同源；查看墙体无动作，失能者不产生移动反应风险', () => {
    const { b } = tacticalFixture(), a = b.byId('a');
    b.byId('d').name = b.byId('b').name;
    const ability = a.abilities.find((a) => a.definitionId === 'bp-firestorm')!;
    const view: TacticalView = { mode: ability.id, selectedId: 'a', targetId: 'b' };
    const preview = tacticalSelection(b, view).target!;
    expect(preview.enabled).toBe(true);
    expect(preview.preview?.areaTargetIds).toEqual(['b', 'd']);
    const areaDamage = preview.preview!.areaPreviews!.map((p) => p.expectedDamage);
    expect(areaDamage[0]).toBeGreaterThan(0); expect(areaDamage[0]).toBeLessThan(areaDamage[1]!);
    expect(renderTacticalBattle(b, view).match(/class="grid-cell [^"]*area-hit/g)).toHaveLength(2);
    const result = b.useAbility('a', ability.id, 'b');
    expect(result.ok).toBe(true);
    expect(result.resolutions.map((r) => r.defenderId)).toEqual(preview.preview!.areaTargetIds);
    selectTacticalElement(b, view, { cell: 29 });
    expect(renderTacticalBattle(b, view)).toContain('地面不可通行');
    const { b: movement } = tacticalFixture();
    const foe = movement.byId('b'); foe.pos = 38; foe.weapon = { id: 'blade', name: '近战剑', range: 0, baseDice: '1d6' };
    expect(movement.getActionOptions('b').find((o) => o.id === 'weapon')?.range?.max).toBe(1);
    expect(movement.pathPreview('a', 46).risks).toHaveLength(1);
    foe.conditions.push({ id: 'stunned', dur: 2 });
    expect(movement.pathPreview('a', 46).risks).toHaveLength(0);
  });
});
